[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[build.processing]
  skip_processing = true

[[plugins]]
  package = "@netlify/plugin-nextjs"